name: PHP CI
on:
  push:
    branches: [ master ]
  status: 
  workflow_run:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: make install; make lint;
